name: Release Automation

on:
  push:
    tags:
      - 'v*'  # trigger workflow when tag starts with "v" (ex: v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          zip -r release-${{ env.RELEASE_VERSION }}.zip . \
            -x ".git/*" ".gitignore" ".github/*" "tests/*" \
            ".venv/*" "*/__pycache__/*" "*.zip" "*.tgz"

      - name: Create TGZ archives
        run: |
          tar -czvf release-${{ env.RELEASE_VERSION }}.tgz \
            --exclude=".git" --exclude=".gitignore" --exclude=".github" --exclude="tests" \
            --exclude=".venv" --exclude="*/__pycache__" --exclude="*.zip" --exclude="*.tgz" .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-${{ env.RELEASE_VERSION }}.zip
            release-${{ env.RELEASE_VERSION }}.tar.gz
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          #body: |
          #  ## Changelog
          #  *(insert CHANGELOG.md.)*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}